//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeOpen.iiko.Back.Temperature.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://server.serviceinspector.ru/api/0/inspector/get_temperature_report?org_id=" +
            "c0bcedb6-99d0-425f-a37f-34013d0c8cfd&template_id=600e3215-7e21-4df3-8434-0e0b62b" +
            "6bf09&token=pTw0gyoVT_xtTV3LVZnaGBCKskNtadEI6Pie-IA1Bj4")]
        public string GetTemperatureUrl {
            get {
                return ((string)(this["GetTemperatureUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6ac394d9-ab89-45bc-b617-74cf35dcfe36")]
        public string StoreId {
            get {
                return ((string)(this["StoreId"]));
            }
        }
    }
}
